version: '3.8'

volumes:
  postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    tty: true
    volumes:
      - type: bind
        source: .
        target: /campfire
    ports:
      - "3000:3000"
    depends_on:
      - redis

  db:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

  redis:
    image: redis:latest
    tty: true
    ports:
      - "6379:6379"
    depends_on:
      - db
