development: &default
  adapter:  postgresql
  database: campfire_development
  username: postgres
  encoding: unicode
  host: db
  password: postgres_password

test:
  <<: *default
  database: campfire_test

production:
  <<: *default
  database: campfire_production
  username: campfire
  password: <%= ENV['CAMPFIRE_DATABASE_PASSWORD'] %>
